name = "InfinityInts"
uuid = "fd51e52e-333b-4b47-aa1f-a72a59653443"
repo = "https://github.com/JeffreySarnoff/InfinityInts.jl.git"
keywords = ["julia", "math", "integers", "infinity"]
author = "Jeffrey Sarnoff"
license = "MIT"
version = "v0.1.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "1"
